package lightcontrol;

import com.panamahitek.ArduinoException;
import com.panamahitek.PanamaHitek_Arduino;     //Se importa librería de conexión a Arduino
import java.awt.Color;
import java.awt.Point;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;

public class LightsFrame extends javax.swing.JFrame {
    
    PanamaHitek_Arduino ino;

    private Color mTransparent;
    private Color gris, azul;
    private Point mpoint;
    ImageDecore aula1, aula2, aula3;
    private int estado, estado1 = 10, estado2 = 20, estado3 = 30;
    
    public LightsFrame() {
        mTransparent = new Color(0,0,0,0);
        gris = new Color(153,153,153);
        azul = new Color(51,0,255);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        paneCasa.setBackground(mTransparent);
        setBackground(mTransparent);
        //Configuración del puerto y velocidad de trabajo del Arduino
        ino = new PanamaHitek_Arduino();
        try {
            ino.arduinoRXTX("COM3", 9600, listener);
        } catch (ArduinoException ex) {
            System.out.println(ex.getMessage());
        }
        //Se pinta el panel que tiene la imagen School
        ImageDecore fondo = new ImageDecore(paneCasa, "/image/escuela.png");
        paneCasa.add(fondo).repaint();
        paneCasa.setOpaque(false);
        paneCasa.setBorder(null);
        paneCasa.setBackground(mTransparent);
        //Se pinta el icono de la X para cerrar ventana
        ImageDecore close = new ImageDecore(paneClose, "/image/exit.png");
        paneClose.add(close).repaint();
        paneClose.setOpaque(false);
        paneClose.setBorder(null);
        paneClose.setBackground(mTransparent);
        //Se pinta en gris el panel que va detras de la imagen School para simular luz apagada del bloque de laboratorios
        paneCasa.setVisible(false);
        paneLucesLab.setBackground(gris);
        paneCasa.setVisible(true);
        //Se pinta la imagen de laboratorio gris en el boton de laboratorios
        aula1 = new ImageDecore(paneAula1, "/image/aulaOFF.png");
        paneAula1.add(aula1).repaint();
        paneAula1.setOpaque(false);
        paneAula1.setBorder(null);
        paneAula1.setBackground(mTransparent);        
        //Se pinta en gris el panel que va detras de la imagen School para simular luz apagada del bloque de Aulas
        paneCasa.setVisible(false);
        paneLucesAulas.setBackground(gris);
        paneCasa.setVisible(true);
        //Se pinta la imagen de aula gris en el boton de Aulas
        aula2 = new ImageDecore(paneAula2, "/image/aulaOFF.png");
        paneAula2.add(aula2).repaint();
        paneAula2.setOpaque(false);
        paneAula2.setBorder(null);
        paneAula2.setBackground(mTransparent);
        //Se pinta en gris el panel que va detras de la imagen School para simular luz apagada del bloque de Oficinas
        paneCasa.setVisible(false);
        paneLucesOfi.setBackground(gris);
        paneCasa.setVisible(true);
        //Se pinta la imagen de aula gris en el boton de Oficinas
        aula3 = new ImageDecore(paneAula3, "/image/aulaOFF.png");
        paneAula3.add(aula3).repaint();
        paneAula3.setOpaque(false);
        paneAula3.setBorder(null);
        paneAula3.setBackground(mTransparent);
    }
    
    SerialPortEventListener listener = new SerialPortEventListener() {      //Recepción de datos
        @Override
        public void serialEvent(SerialPortEvent spe) {
            try {
                if(ino.isMessageAvailable()){
                    estado = Integer.parseInt(ino.printMessage());//Se guarda la lectura del puerto en una variable
                    if(estado == 10) estado1 = 10;                //Según ese dato, se le da valor a los estados de las aulas
                    if(estado == 11) estado1 = 11;
                    if(estado == 20) estado2 = 20;
                    if(estado == 21) estado2 = 21;
                    if(estado == 30) estado3 = 30;
                    if(estado == 31) estado3 = 31;
                    System.out.println("Esdado: "+estado);
                }
            } catch (SerialPortException | ArduinoException ex) {
                System.out.println(ex.getMessage());
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneCasa = new javax.swing.JPanel();
        paneClose = new javax.swing.JPanel();
        paneLucesLab = new javax.swing.JPanel();
        paneLucesAulas = new javax.swing.JPanel();
        paneLucesOfi = new javax.swing.JPanel();
        lblOficinas = new javax.swing.JLabel();
        lblAula = new javax.swing.JLabel();
        lblLaboratorio = new javax.swing.JLabel();
        paneAula2 = new javax.swing.JPanel();
        paneAula1 = new javax.swing.JPanel();
        paneAula3 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneCasa.setPreferredSize(new java.awt.Dimension(665, 336));
        paneCasa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paneCasaMouseDragged(evt);
            }
        });
        paneCasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneCasaMousePressed(evt);
            }
        });

        paneClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneCloseLayout = new javax.swing.GroupLayout(paneClose);
        paneClose.setLayout(paneCloseLayout);
        paneCloseLayout.setHorizontalGroup(
            paneCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        paneCloseLayout.setVerticalGroup(
            paneCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paneCasaLayout = new javax.swing.GroupLayout(paneCasa);
        paneCasa.setLayout(paneCasaLayout);
        paneCasaLayout.setHorizontalGroup(
            paneCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCasaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paneClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        paneCasaLayout.setVerticalGroup(
            paneCasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneCasaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(paneClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        paneLucesLab.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout paneLucesLabLayout = new javax.swing.GroupLayout(paneLucesLab);
        paneLucesLab.setLayout(paneLucesLabLayout);
        paneLucesLabLayout.setHorizontalGroup(
            paneLucesLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );
        paneLucesLabLayout.setVerticalGroup(
            paneLucesLabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        paneLucesAulas.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout paneLucesAulasLayout = new javax.swing.GroupLayout(paneLucesAulas);
        paneLucesAulas.setLayout(paneLucesAulasLayout);
        paneLucesAulasLayout.setHorizontalGroup(
            paneLucesAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );
        paneLucesAulasLayout.setVerticalGroup(
            paneLucesAulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        paneLucesOfi.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout paneLucesOfiLayout = new javax.swing.GroupLayout(paneLucesOfi);
        paneLucesOfi.setLayout(paneLucesOfiLayout);
        paneLucesOfiLayout.setHorizontalGroup(
            paneLucesOfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        paneLucesOfiLayout.setVerticalGroup(
            paneLucesOfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        lblOficinas.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblOficinas.setForeground(new java.awt.Color(153, 153, 153));
        lblOficinas.setText("Oficinas");

        lblAula.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblAula.setForeground(new java.awt.Color(153, 153, 153));
        lblAula.setText("Aulas");

        lblLaboratorio.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblLaboratorio.setForeground(new java.awt.Color(153, 153, 153));
        lblLaboratorio.setText("Laboratorios");

        paneAula2.setToolTipText("Clic para encender aulas");
        paneAula2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneAula2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneAula2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneAula2Layout = new javax.swing.GroupLayout(paneAula2);
        paneAula2.setLayout(paneAula2Layout);
        paneAula2Layout.setHorizontalGroup(
            paneAula2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );
        paneAula2Layout.setVerticalGroup(
            paneAula2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        paneAula1.setToolTipText("");
        paneAula1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneAula1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneAula1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneAula1Layout = new javax.swing.GroupLayout(paneAula1);
        paneAula1.setLayout(paneAula1Layout);
        paneAula1Layout.setHorizontalGroup(
            paneAula1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        paneAula1Layout.setVerticalGroup(
            paneAula1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        paneAula3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneAula3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneAula3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneAula3Layout = new javax.swing.GroupLayout(paneAula3);
        paneAula3.setLayout(paneAula3Layout);
        paneAula3Layout.setHorizontalGroup(
            paneAula3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );
        paneAula3Layout.setVerticalGroup(
            paneAula3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneAula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLaboratorio))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneAula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblAula)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblOficinas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(paneAula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(244, 244, 244)
                    .addComponent(paneLucesAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(paneLucesLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(448, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(435, 435, 435)
                    .addComponent(paneLucesOfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(71, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paneAula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paneAula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAula)
                            .addComponent(lblOficinas)
                            .addComponent(lblLaboratorio)))
                    .addComponent(paneAula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(152, 152, 152)
                    .addComponent(paneLucesAulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(141, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(paneLucesLab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(151, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(202, 202, 202)
                    .addComponent(paneLucesOfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paneCasaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCasaMousePressed
        mpoint = evt.getPoint();
        getComponentAt(mpoint);  
    }//GEN-LAST:event_paneCasaMousePressed
    
    //Metodo que permite arrastrar la la app por toda la ventana
    private void paneCasaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCasaMouseDragged
        int currentX = this.getLocation().x;
        int currentY = this.getLocation().y;
        //Se calcula cuántos pixeles en X y Y se ha movido el JFrame
        int moveX = (currentX + evt.getX()) - (currentX + mpoint.x);
        int moveY = (currentY + evt.getY()) - (currentY + mpoint.y);
        //Se calcula las nuevas posiciones en X y Y
        int x = currentX + moveX;
        int y = currentY + moveY;
        //Se pasan las nuevas posiciones al JFrame
        this.setLocation(x, y);
    }//GEN-LAST:event_paneCasaMouseDragged

    //Salir al dar clix en la X
    private void paneCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_paneCloseMouseClicked

    //Funcionalidad al dar click en el botón Laboratorios
    private void paneAula1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneAula1MouseClicked
        
        if(estado1 == 10){          //Si el led1 esta apagado
            try {
                ino.sendData("11"); //Envíe por el puesto COM3, encienda led1
            } catch (ArduinoException | SerialPortException ex) {
                System.out.println(ex.getMessage());
            }
            //y cambie la apariencia de los paneles e imagenes para mostar al usuario que área está encendida.
            paneCasa.setVisible(false);
            paneLucesLab.setBackground(Color.YELLOW);
            paneCasa.setVisible(true);
            
            aula1.setVisible(false);
            aula1 = new ImageDecore(paneAula1, "/image/aulaON.png");
            paneAula1.add(aula1).repaint();
            paneAula1.setOpaque(false);
            paneAula1.setBorder(null);
            paneAula1.setBackground(mTransparent);
            lblLaboratorio.setForeground(azul);            
        }else if(estado1 == 11){        //Si el led1 esta encendido
            try {
                ino.sendData("10");     //Envíe por el puesto COM3, apague led1
            } catch (ArduinoException | SerialPortException ex) {
                System.out.println(ex.getMessage());
            }
            //y cambie la apariencia de los paneles e imagenes para mostar al usuario que área está apagada.
            paneCasa.setVisible(false);
            paneLucesLab.setBackground(gris);
            paneCasa.setVisible(true);
            
            aula1.setVisible(false);
            aula1 = new ImageDecore(paneAula1, "/image/aulaOFF.png");
            paneAula1.add(aula1).repaint();
            paneAula1.setOpaque(false);
            paneAula1.setBorder(null);
            paneAula1.setBackground(mTransparent);  
            lblLaboratorio.setForeground(gris);
        }
    }//GEN-LAST:event_paneAula1MouseClicked
    
    //Funcionalidad al dar click en el botón Aulas, tal como la función anterior.
    private void paneAula2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneAula2MouseClicked
        if(estado2 == 20){
            try {
                ino.sendData("21");
            } catch (ArduinoException | SerialPortException ex) {
                System.out.println(ex.getMessage());
            }
            paneCasa.setVisible(false);
            paneLucesAulas.setBackground(Color.YELLOW);
            paneCasa.setVisible(true);
            
            aula2.setVisible(false);
            aula2 = new ImageDecore(paneAula2, "/image/aulaON.png");
            paneAula2.add(aula2).repaint();
            paneAula2.setOpaque(false);
            paneAula2.setBorder(null);
            paneAula2.setBackground(mTransparent);  
            lblAula.setForeground(azul);
        }else if(estado2 == 21){
            try {
                ino.sendData("20");
            } catch (ArduinoException | SerialPortException ex) {
                System.out.println(ex.getMessage());
            }
            paneCasa.setVisible(false);
            paneLucesAulas.setBackground(gris);
            paneCasa.setVisible(true);
            
            aula2.setVisible(false);
            aula2 = new ImageDecore(paneAula2, "/image/aulaOFF.png");
            paneAula2.add(aula2).repaint();
            paneAula2.setOpaque(false);
            paneAula2.setBorder(null);
            paneAula2.setBackground(mTransparent);    
            lblAula.setForeground(gris);          
        }
    }//GEN-LAST:event_paneAula2MouseClicked

    //Funcionalidad al dar click en el botón Oficinas, tal como la función anterior.
    private void paneAula3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneAula3MouseClicked
        if(estado3 == 30){
            try {
                ino.sendData("31");
            } catch (ArduinoException | SerialPortException ex) {
                System.out.println(ex.getMessage());
            }
            paneCasa.setVisible(false);
            paneLucesOfi.setBackground(Color.YELLOW);
            paneCasa.setVisible(true);
            
            aula3.setVisible(false);
            aula3 = new ImageDecore(paneAula2, "/image/aulaON.png");
            paneAula3.add(aula3).repaint();
            paneAula3.setOpaque(false);
            paneAula3.setBorder(null);
            paneAula3.setBackground(mTransparent);   
            lblOficinas.setForeground(azul);           
        }else if(estado3 == 31){
            try {
                ino.sendData("30");
            } catch (ArduinoException | SerialPortException ex) {
                System.out.println(ex.getMessage());
            }
            paneCasa.setVisible(false);
            paneLucesOfi.setBackground(gris);
            paneCasa.setVisible(true);
            
            aula3.setVisible(false);
            aula3 = new ImageDecore(paneAula3, "/image/aulaOFF.png");
            paneAula3.add(aula3).repaint();
            paneAula3.setOpaque(false);
            paneAula3.setBorder(null);
            paneAula3.setBackground(mTransparent);    
            lblOficinas.setForeground(gris);       
        }
    }//GEN-LAST:event_paneAula3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LightsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LightsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAula;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblOficinas;
    private javax.swing.JPanel paneAula1;
    private javax.swing.JPanel paneAula2;
    private javax.swing.JPanel paneAula3;
    private javax.swing.JPanel paneCasa;
    private javax.swing.JPanel paneClose;
    private javax.swing.JPanel paneLucesAulas;
    private javax.swing.JPanel paneLucesLab;
    private javax.swing.JPanel paneLucesOfi;
    // End of variables declaration//GEN-END:variables
}
