package lightcontrol;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Point;
import java.awt.Rectangle;
import java.security.Key;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.xml.bind.DatatypeConverter;

public class Login extends javax.swing.JFrame {

    ImageDecore btnLogin;
    private Color mTransparent;
    private Point mpoint;
    Conexion conexion = new Conexion();
    PreparedStatement ps;
    ResultSet rs;
    CallableStatement cst = null;
    private static String  ENCRYPT_KEY = "ligt-Contr@l2022";

    public Login() {
        mTransparent = new Color(0,0,0,0);
        setUndecorated(true);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        setBackground(mTransparent);
                        
        ImageDecore fondo = new ImageDecore(paneBackground, "/image/loginBackground.png");
        paneBackground.add(fondo).repaint();
        paneBackground.setOpaque(false);
        paneBackground.setBorder(null);
        paneBackground.setBackground(mTransparent);  
        
        ImageDecore close = new ImageDecore(paneClose, "/image/exit.png");
        paneClose.add(close).repaint();
        paneClose.setOpaque(false);
        paneClose.setBorder(null);
        paneClose.setBackground(mTransparent);
        
        ImageDecore user = new ImageDecore(paneUser, "/image/loginUser.png");
        paneUser.add(user).repaint();
        paneUser.setOpaque(false);
        paneUser.setBorder(null);
        paneUser.setBackground(mTransparent); 
        
        txtUser.setBorder(null); 
        txtUser.requestFocus();
        txtPassword.setBorder(null);
        
        btnLogin = new ImageDecore(paneButton, "/image/btnLogin.png");
        paneButton.add(btnLogin).repaint();
        paneButton.setOpaque(false);
        paneButton.setBorder(null);
        paneButton.setBackground(mTransparent); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneBackground = new javax.swing.JPanel();
        paneClose = new javax.swing.JPanel();
        paneUser = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        paneButton = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        paneBackground.setPreferredSize(new java.awt.Dimension(400, 400));
        paneBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                paneBackgroundMouseDragged(evt);
            }
        });
        paneBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneBackgroundMousePressed(evt);
            }
        });

        paneClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneCloseLayout = new javax.swing.GroupLayout(paneClose);
        paneClose.setLayout(paneCloseLayout);
        paneCloseLayout.setHorizontalGroup(
            paneCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        paneCloseLayout.setVerticalGroup(
            paneCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        txtUser.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 0, 102));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout paneUserLayout = new javax.swing.GroupLayout(paneUser);
        paneUser.setLayout(paneUserLayout);
        paneUserLayout.setHorizontalGroup(
            paneUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneUserLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(paneUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        paneUserLayout.setVerticalGroup(
            paneUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneUserLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        paneButton.setToolTipText("Log in");
        paneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paneButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paneButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                paneButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paneButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout paneButtonLayout = new javax.swing.GroupLayout(paneButton);
        paneButton.setLayout(paneButtonLayout);
        paneButtonLayout.setHorizontalGroup(
            paneButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );
        paneButtonLayout.setVerticalGroup(
            paneButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btnRegistro.setBackground(new Color(0,0,0,0));
        btnRegistro.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setText("Registrarse");
        btnRegistro.setToolTipText("New user");
        btnRegistro.setBorder(null);
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneBackgroundLayout = new javax.swing.GroupLayout(paneBackground);
        paneBackground.setLayout(paneBackgroundLayout);
        paneBackgroundLayout.setHorizontalGroup(
            paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBackgroundLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneBackgroundLayout.createSequentialGroup()
                        .addComponent(btnRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paneUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(paneClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        paneBackgroundLayout.setVerticalGroup(
            paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBackgroundLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(paneClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(paneUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistro))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paneBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneBackgroundMousePressed
       mpoint = evt.getPoint();
        getComponentAt(mpoint);        
    }//GEN-LAST:event_paneBackgroundMousePressed

    private void paneBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneBackgroundMouseDragged
        int currentX = this.getLocation().x;
        int currentY = this.getLocation().y;
        //Se calcula cuántos pixeles en X y Y se ha movido el JFrame
        int moveX = (currentX + evt.getX()) - (currentX + mpoint.x);
        int moveY = (currentY + evt.getY()) - (currentY + mpoint.y);
        //Se calcula las nuevas posiciones en X y Y
        int x = currentX + moveX;
        int y = currentY + moveY;
        //Se pasan las nuevas posiciones al JFrame
        this.setLocation(x, y);        
    }//GEN-LAST:event_paneBackgroundMouseDragged

    private void paneCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_paneCloseMouseClicked

    private void paneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneButtonMouseEntered
        btnLogin.setVisible(false);
        btnLogin = new ImageDecore(paneButton, "/image/btnLogin2.png");
        paneButton.add(btnLogin).repaint();
        paneButton.setOpaque(false);
        paneButton.setBorder(null);
        paneButton.setBackground(mTransparent); 
    }//GEN-LAST:event_paneButtonMouseEntered

    private void paneButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneButtonMouseExited
        btnLogin.setVisible(false);
        btnLogin = new ImageDecore(paneButton, "/image/btnLogin.png");
        paneButton.add(btnLogin).repaint();
        paneButton.setOpaque(false);
        paneButton.setBorder(null);
        paneButton.setBackground(mTransparent);    
    }//GEN-LAST:event_paneButtonMouseExited

    private void paneButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneButtonMousePressed
        btnLogin.setVisible(false);
        btnLogin = new ImageDecore(paneButton, "/image/btnLogin.png");
        paneButton.add(btnLogin).repaint();
        paneButton.setOpaque(false);
        paneButton.setBorder(null);
        paneButton.setBackground(mTransparent); 
    }//GEN-LAST:event_paneButtonMousePressed

    private void paneButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneButtonMouseReleased
        btnLogin.setVisible(false);
        btnLogin = new ImageDecore(paneButton, "/image/btnLogin2.png");
        paneButton.add(btnLogin).repaint();
        paneButton.setOpaque(false);
        paneButton.setBorder(null);
        paneButton.setBackground(mTransparent); 
    }//GEN-LAST:event_paneButtonMouseReleased

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
        setVisible(false);
        btnRegistro.setBackground(new Color(14,125,233));
        Registrar nuevo = new Registrar();
        nuevo.setVisible(true);
    }//GEN-LAST:event_btnRegistroMouseClicked

    private void paneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneButtonMouseClicked
        String user = txtUser.getText();
        String pass = txtPassword.getText();
        
        //Validación de campos obligatorios en la Basde de Datos
        if(user.equals("") || pass.equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese usuario y contraseña", "Campos vacios", JOptionPane.ERROR_MESSAGE);            
        }else{
            try{
                cst = conexion.con.prepareCall("{CALL spLogin (?,?,?,?,?,?)}");

                cst.setString(1,user);
                cst.setString(2, encript(pass));
                cst.setString(3, "ligt-Contr@l2022");  
                //Se define los tipos de los parametros de salida del procedimiento almacenado
                cst.registerOutParameter(4, java.sql.Types.VARCHAR);
                cst.registerOutParameter(5, java.sql.Types.VARCHAR);
                cst.registerOutParameter(6, java.sql.Types.INTEGER);
                
                cst.execute();
                String usuario = cst.getString(4);
                String password = decrypt(cst.getString(5));
                int rol = cst.getInt(6);
                System.out.println(usuario+", "+password+ ", "+rol);
                if(usuario.equals(user) && password.equals(pass)){
                    setVisible(false);
                    LightsFrame run = new LightsFrame();
                    run.setVisible(true);
                    JOptionPane.showMessageDialog(this, "Bienvenido a Ligh Control", "Ligh Control", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta", "Datos incorrectos", JOptionPane.ERROR_MESSAGE);
                }
            //con.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrecta", "Datos incorrectos", JOptionPane.ERROR_MESSAGE);                
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_paneButtonMouseClicked

    private static String encript(String text) throws Exception {	
        Key aesKey = new SecretKeySpec(ENCRYPT_KEY.getBytes(), "AES");

        Cipher cipher = Cipher.getInstance("AES");
        cipher.init(Cipher.ENCRYPT_MODE, aesKey);

        byte[] encrypted = cipher.doFinal(text.getBytes());

        return DatatypeConverter.printBase64Binary(encrypted);
    }
    
    private static String decrypt(String encrypted) throws Exception {
        byte[] encryptedBytes = DatatypeConverter.parseBase64Binary(encrypted.replace("\n", "") );

        Key aesKey = new SecretKeySpec(ENCRYPT_KEY.getBytes(), "AES");

        Cipher cipher = Cipher.getInstance("AES");
        cipher.init(Cipher.DECRYPT_MODE, aesKey);

        String decrypted = new String(cipher.doFinal(encryptedBytes));

        return decrypted;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel paneBackground;
    private javax.swing.JPanel paneButton;
    private javax.swing.JPanel paneClose;
    private javax.swing.JPanel paneUser;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
