package lightcontrol;

import java.awt.Color;
import java.awt.Point;

public class Registrar extends javax.swing.JFrame {
    
    private Color mTransparent;
    private Point mpoint;

    public Registrar() {
        mTransparent = new Color(0,0,0,0);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        jPanel1.setBackground(mTransparent);
        lblFondo.setBackground(mTransparent);
        setBackground(mTransparent);
        
        ImageDecore fondo = new ImageDecore(paneClose, "/image/exit.png");
        paneClose.add(fondo).repaint();
        paneClose.setOpaque(false);
        paneClose.setBorder(null);
        paneClose.setBackground(mTransparent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneClose = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        lblRegistrar = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(295, 560));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paneClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneCloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout paneCloseLayout = new javax.swing.GroupLayout(paneClose);
        paneClose.setLayout(paneCloseLayout);
        paneCloseLayout.setHorizontalGroup(
            paneCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );
        paneCloseLayout.setVerticalGroup(
            paneCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(paneClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        txtCedula.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(255, 51, 51));
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCedula.setToolTipText("");
        txtCedula.setBorder(null);
        txtCedula.setName("Nombres"); // NOI18N
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 160, -1));

        txtNombres.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(255, 51, 51));
        txtNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombres.setToolTipText("");
        txtNombres.setBorder(null);
        txtNombres.setName("Nombres"); // NOI18N
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 160, 20));

        txtApellidos.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(255, 51, 51));
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidos.setToolTipText("");
        txtApellidos.setBorder(null);
        txtApellidos.setName("Nombres"); // NOI18N
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 160, 20));

        txtUser.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 51, 51));
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUser.setToolTipText("");
        txtUser.setBorder(null);
        txtUser.setName("Nombres"); // NOI18N
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 344, 160, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI Black", 1, 11)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 51, 51));
        txtPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPassword.setToolTipText("");
        txtPassword.setBorder(null);
        txtPassword.setName("Nombres"); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 396, 160, 20));

        lblRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 51, 51));
        lblRegistrar.setText("Registrar");
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 444, 60, 20));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/registerUser.png"))); // NOI18N
        lblFondo.setPreferredSize(new java.awt.Dimension(295, 560));
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 295, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int currentX = this.getLocation().x;
        int currentY = this.getLocation().y;
        //Se calcula cuántos pixeles en X y Y se ha movido el JFrame
        int moveX = (currentX + evt.getX()) - (currentX + mpoint.x);
        int moveY = (currentY + evt.getY()) - (currentY + mpoint.y);
        //Se calcula las nuevas posiciones en X y Y
        int x = currentX + moveX;
        int y = currentY + moveY;
        //Se pasan las nuevas posiciones al JFrame
        this.setLocation(x, y);  
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        mpoint = evt.getPoint();
        getComponentAt(mpoint);  
    }//GEN-LAST:event_jPanel1MousePressed

    private void paneCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_paneCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JPanel paneClose;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
